const productos = [
  {
    id: 1,
    image: "https://via.placeholder.com/150",
    name: "Laptop",
    description: "Ideal para tareas cotidianas y navegación.",
    stock: 15,
    price: 450.0,
    category: "Electrónica",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    name: "Teléfono ",
    description: "Pantalla de 6.5 pulgadas, cámara dual.",
    stock: 30,
    price: 299.99,
    category: "Electrónica",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150",
    name: "Auriculares Bluetooth",
    description: "Con cancelación de ruido y batería de larga duración.",
    stock: 25,
    price: 59.99,
    category: "Accesorios",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150",
    name: "Mochila",
    description: "Resistente al agua con múltiples compartimentos.",
    stock: 20,
    price: 39.5,
    category: "Accesorios",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/150",
    name: "Reloj Deportivo",
    description: "Con monitoreo de actividad física y notificaciones.",
    stock: 18,
    price: 75.0,
    category: "Accesorios",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/150",
    name: "Zapatillas Deportivas",
    description: "Suela de goma antideslizante y diseño ligero.",
    stock: 10,
    price: 89.99,
    category: "Ropa",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/150",
    name: "Remera Overzice",
    description: "100% algodón, cómoda y transpirable.",
    stock: 50,
    price: 15.0,
    category: "Ropa",
  },
  {
    id: 8,
    image: "https://via.placeholder.com/150",
    name: "Botella Térmica",
    description: "Mantiene líquidos fríos o calientes hasta 12 horas.",
    stock: 35,
    price: 25.0,
    category: "Hogar",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/150",
    name: "Cafetera",
    description: "Capacidad para 10 tazas con función de temporizador.",
    stock: 12,
    price: 120.0,
    category: "Electrodomésticos",
  },
  {
    id: 10,
    image: "https://via.placeholder.com/150",
    name: "Silla de Oficina",
    description: "Diseñada para largas horas de trabajo con soporte lumbar.",
    stock: 8,
    price: 150.0,
    category: "Muebles",
  },
];
export default productos;
